[bugfix] solve undefined reference to sttic constexpr class member, because it was used in an inline const & function requiring it's address and therefore a definition ...